### ISSUE TITLE
Fail to Open the Notebook of MyiPad

### ISSUE THREAD

**Issue by nik-nul** [dump-automaton/MyiPad-Plugin#17]
Version of MyiPad: 5.2.3.52408
Version of Plugin: 5.0
Original Hardware: Lenovo Tablets TB-X605M
Original Software Version: TB-X605M_RF01_20209030_NingBoRuiYi

When trying to use "Notebook" function in the dropzone, it prompts "Unable to open the notebook. The `Notebook' function is currently disabled, cannot be used.", whereas notebook function works properly on the original hardware distributed by school. The issue recurs steadily every time I try regardless of whether the physical machine is used or not.

P.S.: Message System is not connected according to the bottom right corner, but "Self-Learning", "Query-Answering Online" and "My Repo" function works well.

**Comment by Richard-Zheng** [comment]
Could you provide your school domain? (you can send to me by email)

**Comment by Richard-Zheng** [comment]
Also, could you provide some screenshot for the issue? 

You may also try more MyiPad version (higher or lower) for quick fix.

**Comment by nik-nul** [comment]
I've sent you an email including some more detailed information :)

**Comment by Richard-Zheng** [comment]
Turning off "Allow all permissions" can solve this issue.
