### ISSUE TITLE
消息系统异常

### ISSUE THREAD

**Issue by clxhsa** [dump-automaton/MyiPad-Plugin#21]
在第三方设备使用MyiPad-Plugin硬件伪装登陆少年派后显示消息系统异常，可以收到自主学习资源推送，可以刷新出历史消息记录，但无法接收新消息
少年派版本：5.2.3.52361/5.2.3.52408
MyiPad-Plugin版本：0.5
![Screenshot_2022-11-01-16-31-43-362_com.netspace.myipad.jpg](https://user-images.githubusercontent.com/105988602/199191960-d3de76a6-d751-4c32-aacb-fec7cbe5a001.jpg)
![Screenshot_2022-11-01-16-32-06-485_com.netspace.myipad.jpg](https://user-images.githubusercontent.com/105988602/199192039-2247dac2-23a9-41fd-adec-6b51791991cd.jpg)
![Screenshot_2022-11-01-16-32-13-439_com.netspace.myipad.jpg](https://user-images.githubusercontent.com/105988602/199192054-cb39c6ff-c501-4971-9943-d208bd8bf9b2.jpg)

**Comment by Richard-Zheng** [comment]
取消勾选 IM Service 以及所有标了实验性的功能再试。如果问题消失那这个是符合预期的情况，请 close issue.

**Comment by clxhsa** [comment]
> 取消勾选 IM Service 以及所有标了实验性的功能再试。如果问题消失那这个是符合预期的情况，请 close issue.

试过了还是不行，但现在刷了安卓10可以正常用了，之前试了安卓11和12都不行，可能是系统问题吧

**Comment by Richard-Zheng** [comment]
> > 取消勾选 IM Service 以及所有标了实验性的功能再试。如果问题消失那这个是符合预期的情况，请 close issue.
> 
> 试过了还是不行，但现在刷了安卓10可以正常用了，之前试了安卓11和12都不行，可能是系统问题吧

说一下用的啥 Xposed 框架，以及看看有没有 crash log（不过应该没有）。
